### PR TITLE
Copy button near ready to try out

### PR DESCRIPTION
**Pull request by sarthak-nande**
I made some changes in style.css and the landing.js file 

- Solve the problem of Ready to try out? section from the landing page.
- Solve the issue of Subscribe to our newsletter problem.

Checkout these changes once Thank you!

### CODE REVIEW

**Comment by garg3133** [comment]
@sarthu210 The issue in the UI of "Ready to try out?" section is still there:

image

And the issue with substack is resolved now in PR #87.

**Comment by sarthu210** [comment]
> @sarthu210 The issue in the UI of "Ready to try out?" section is still there:
> 
> image
> 
> And the issue with substack is resolved now in PR #87.

Hi sir the issue is still persist after merging PR#87 you can check by submitting wrong email. I resolve that issue in my request. I request you to check my code it is optimal ThankYou!

**Comment by garg3133** [comment]
@sarthu210 The changes are merged but not deployed yet, that's why it's still not appearing on the website.

Also, the changes you've made for "Ready to try out?" section are not ideal, because you've changed the range of media query itself, which affects the whole website and not just that section.

**Comment by sarthu210** [comment]
> @sarthu210 The changes are merged but not deployed yet, that's why it's still not appearing on the website.
> 
> Also, the changes you've made for "Ready to try out?" section are not ideal, because you've changed the range of media query itself, which affects the whole website and not just that section.

This is #87 PR deployed changes link https://github.com/nightwatchjs/nightwatch-www/pull/86#issuecomment-1991453519 you can try that I said earlier about this PR

**Comment by sarthu210** [comment]
I also saw one another thing in ready to try section that is if you click get started button you what happens after that for few sec.

**Comment by vaibhavsingh97** [comment]
@sarthu210 I see that the iframe currently has a lot of content, but all we really need is the input box and the subscribe button.
image

**Comment by sarthu210** [comment]
> @sarthu210 I see that the iframe currently has a lot of content, but all we really need is the input box and the subscribe button. image

Sir shall try to make it more perfect.

**Comment by garg3133** [comment]
@sarthu210 I think the substack UI is fine for now, it only malperforms on entering wrong email and then also it gives enough space to edit the email and click on the Subscribe button again. We really don't want to show everything from the substack UI, just the important stuff. If you can solve the UI issue with these conditions, then you're most welcome to propose a solution.

> I also saw one another thing in ready to try section that is if you click get started button you can see what happens after that for few sec.

For this comment, I see what you're saying. The UI gets distorted during the delay it takes for the "Get Started" page to be loaded.

image

Please feel free to work on this. As for the issue of UI getting distorted while changing the screen width, that has been fixed in #85.

Also, please create separate PRs for individual issues.

**Pull request closed without merging**
